### ISSUE TITLE
Unable to connect to server? How do you setup SMTP and IMAP? Gmail?

### ISSUE THREAD

**Issue by vladimirs1981** [Apress/modern-full-stack-development#107]

**Comment by fzammetti** [comment]
Hi,

It looks like Gmail always requires SSL/TLS for SMTP and IMAP connections. Unfortunately, Mailbag was written to only support insecure connections (just because it's simpler and was never meant to be a full-featured email client). I'm frankly not sure what would be involved in making it support secure connections, and therefore Gmail (I have a vague memory of it not being trivial though).

Coincidently, I'm working on a second edition of this book, so I'll add this to my to-do list. Once that book is done, if you're still interested, you'll be able to get the code even without buying the book. Keep an eye out around the end of the year (Apress puts all the code for their books on Github, so shouldn't be hard to find).

Thanks,
Frank
